name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit

    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Security check with Bandit
      run: |
        bandit -r src/app.py --severity-level high

    - name: Build Docker image
      run: |
        docker build -t mon-app .

    - name: Install Docker Scout
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh


    - name: Run Docker Scout
      run: |
        docker scout quickview mon-app

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push mon-app
